name: "postgres_pgadmin_server"
services:

  postgres:
    build:
      context: ./dockerfiles
      dockerfile: postgres.dockerfile
    container_name: postgres_pgadmin_server_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_postgres_user_password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: >
      -c max_connections=200
      -c shared_buffers=256MB
      -c timezone=UTC
      -c client_encoding=UTF8

  dpagepgadmin:
    build:
        context: ./dockerfiles
        dockerfile: dpagepgadmin4.dockerfile
    container_name: postgres_pgadmin_server_pgadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.dev
      - PGADMIN_DEFAULT_PASSWORD=app_pgadmin_password
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_db_data:
  pgadmin_data: